#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>
#include <driver/ledc.h>

#define AUDIO_INPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_16
#define AUDIO_I2S_GPIO_WS GPIO_NUM_45
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_41
#define AUDIO_I2S_GPIO_DIN GPIO_NUM_42
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_40

#define AUDIO_CODEC_PA_PIN GPIO_NUM_46
#define AUDIO_CODEC_I2C_SDA_PIN GPIO_NUM_15
#define AUDIO_CODEC_I2C_SCL_PIN GPIO_NUM_14
#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define EXAMPLE_PIN_NUM_LCD_CS GPIO_NUM_12
#define EXAMPLE_PIN_NUM_LCD_PCLK GPIO_NUM_11
#define EXAMPLE_PIN_NUM_LCD_DATA0 GPIO_NUM_4
#define EXAMPLE_PIN_NUM_LCD_DATA1 GPIO_NUM_5
#define EXAMPLE_PIN_NUM_LCD_DATA2 GPIO_NUM_6
#define EXAMPLE_PIN_NUM_LCD_DATA3 GPIO_NUM_7
#define EXAMPLE_PIN_NUM_LCD_RST GPIO_NUM_8
#define DISPLAY_WIDTH 410
#define DISPLAY_HEIGHT 502
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define TOUCH_RST_PIN GPIO_NUM_9
#define TOUCH_INT_PIN GPIO_NUM_38

#define SDCARD_MOUNT_POINT "/sdcard"
#define SDCARD_CLK_PIN GPIO_NUM_2
#define SDCARD_CMD_PIN GPIO_NUM_1
#define SDCARD_D0_PIN GPIO_NUM_3

#define IMU_QMI8658_ADDR QMI8658_ADDRESS_HIGH

/*
 * Head servos, direct PWM.
 * Change these pins manually here if wiring changes.
 */
#define SERVO_HEAD_YAW_PIN       GPIO_NUM_19
#define SERVO_HEAD_PITCH_PIN     GPIO_NUM_20
#define SERVO_HEAD_YAW_NUM       1
#define SERVO_HEAD_PITCH_NUM     2

#define SERVO_PWM_FREQ_HZ        50
#define SERVO_PWM_SPEED_MODE     LEDC_LOW_SPEED_MODE
#define SERVO_PWM_TIMER          LEDC_TIMER_0
#define SERVO_PWM_RESOLUTION     LEDC_TIMER_14_BIT
#define SERVO_PWM_YAW_CHANNEL    LEDC_CHANNEL_0
#define SERVO_PWM_PITCH_CHANNEL  LEDC_CHANNEL_1

#define SERVO_MIN_ANGLE          0
#define SERVO_MAX_ANGLE          120
#define SERVO_HOME_ANGLE         90
#define SERVO_MIN_PULSE_US       500
#define SERVO_MAX_PULSE_US       2500

#endif // _BOARD_CONFIG_H_
